name: Build and Deploy Full Stack App to Azure Web App - anythingsoundsgood

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # Set up .NET Core environment
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Restore dependencies for all projects (ASGBackend, ASGClient, ASGShared)
      - name: Restore Dependencies
        run: dotnet restore

      # Build all projects (Backend, Blazor, Shared)
      - name: Build Solution
        run: dotnet build --configuration Release

      # Publish the Backend (ASGBackend)
      - name: Publish Backend
        run: dotnet publish ./ASGBackend/ASGBackend.csproj -c Release -o ./publish/ASGBackend

      # Publish the Blazor WebAssembly (ASGClient)
      - name: Publish Blazor WebAssembly
        run: dotnet publish ./ASGClient/ASGClient.csproj -c Release -o ./publish/ASGClient

      # Copy Blazor Frontend to Backend's wwwroot using PowerShell Copy-Item
      - name: Copy Blazor Frontend to Backend's wwwroot using PowerShell Copy-Item
        run: |
          Write-Host "Copying Blazor frontend to Backend wwwroot"
          Copy-Item -Path ./publish/ASGClient/* -Destination ./publish/ASGBackend/wwwroot/ -Recurse -Force
          Write-Host "Copy complete"

      # Upload artifact for deployment job (Backend with Blazor frontend inside wwwroot)
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: net-app
          path: ./publish/ASGBackend

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: net-app
          path: ./deploy  # Download artifact into the 'deploy' directory

      # List downloaded files for debugging
      - name: List downloaded files
        run: |
          Write-Host "Listing downloaded artifact files"
          ls ./deploy
          Write-Host "Listing complete"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D2F3C866E6594F5C9D00AF0CE9FD7B31 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_87B8B694548D4E7FA66A1D58734A8DCC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4E5F9F6FBC904078A687C0EF342EDEB6 }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'anythingsoundsgood'
          slot-name: 'Production'
          package: ./deploy

      - name: Set environment variables
        env:
          ASG_DB_PW: ${{ secrets.ASG_DB_PW }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}          
        run: echo "Environment variables set."
