name: Build and Deploy Full Stack App to Azure Web App - anythingsoundsgood

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # Step 1: Set up .NET Core environment
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Step 2: Restore dependencies for all projects (Backend, Blazor, Shared)
      - name: Restore Dependencies
        run: dotnet restore

      # Step 3: Build all projects (Backend, Blazor, Shared)
      - name: Build Solution
        run: dotnet build --configuration Release

      # Step 4: Publish the Backend (ASGBackend)
      - name: Publish Backend
        run: dotnet publish ./ASGBackend/ASGBackend.csproj -c Release -o ./publish/Backend

      # Step 5: Publish Blazor WebAssembly Frontend (ASGClient)
      - name: Publish Blazor WebAssembly
        run: dotnet publish ./ASGClient/ASGClient.csproj -c Release -o ./publish/Client

      # Step 6: Copy Blazor Frontend to Backend's wwwroot
      - name: Copy Blazor Frontend to Backend's wwwroot
        run: cp -r ./publish/Client/* ./publish/Backend/wwwroot/

      # Step 7: Upload artifact for deployment
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish/Backend

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D2F3C866E6594F5C9D00AF0CE9FD7B31 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_87B8B694548D4E7FA66A1D58734A8DCC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4E5F9F6FBC904078A687C0EF342EDEB6 }}

      - name: Set environment variables
        env:
          ASG_DB_PW: ${{ secrets.ASG_DB_PW }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS_B64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_B64 }}
        run: echo "Environment variables set."

      # Step 8: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'anythingsoundsgood'
          slot-name: 'Production'
          package: ./publish/Backend
